[tasks.install]
description = "Build"
script = ['''
#!/usr/bin/env bash
poetry install
''']

[tasks.lint]
description = "Lint"
script = ['''
#!/usr/bin/env bash
poetry run black ./
''']
dependencies = ["install"]

[tasks.type_check]
description = "Type Check"
script = ['''
#!/usr/bin/env bash
poetry run mypy --config mypy.ini
''']
dependencies = ["install"]

[tasks.import_check]
description = "Import Check"
script = ['''
#!/usr/bin/env bash
poetry run isort . -rc
''']
dependencies = ["install"]

[tasks.pytest]
description = "Test"
script = ['''
#!/usr/bin/env bash
sleep 10
poetry run pytest --verbose -s --cov=src ./tests
''']
dependencies = ["install", "lint"]

[tasks.docker_up]
description = "Docker for Test"
script = ['''
#!/usr/bin/env bash
docker-compose up --detach
''']

[tasks.docker_down]
description = "DynamoDB-local"
script = ['''
#!/usr/bin/env bash
docker-compose down
''']

[tasks.tests]
dependencies = [
    "docker_up",
    "pytest",
    "docker_down"
]